### ISSUE TITLE
Improve documentation for running with upstart/systemd/pm2/docker

### ISSUE THREAD

**Issue by braydonf** [storj/storjshare-daemon#111]
It was not straight forward to find the following from the readme:
1. Example configuration file
2. Location of actual daemon process w/o process management

Also translating the storjshare-cli config into the storjshare-daemon was not documented. The `renterWhitelist` isn't documented or in the code.

**Comment by braydonf** [comment]
Was able to get things upgraded, diff for reference: https://github.com/Storj/integration/pull/3/files

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
