### ISSUE TITLE
Reaper sweep

### ISSUE THREAD

**Issue by ghost** [storj/storjshare-daemon#115]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.4.3
```

Replace the values below using the output from `node --version`.

```
6.9.4
```

Would like to have reaper sweep every 10 hours or so as apposed to 24 hours as seems not catching all dead as ran my manual java script catches 100+ for each of my drives. as having to use Storj_Farmer_Manuall_CleanUp

**Comment by littleskunk** [comment]
On my own farmer I run the reaper every 3 hours but I disabled the compact job. That works very well. I will write a feature request to allow all the different options on the config file.

**Comment by doransmestad** [comment]
@littleskunk  any luck on this?  I'm seeing similar symptoms described in this ticket.  I'm observing massive amount of disk traffic from Storj - on the order of 16TB per week.  I'm only storing about 8TB of Storj data total, so these numbers are a bit alarming.  I've had to stop/start the storjshare service from time to time to halt whatever is happening and give performance back to my NAS array. 

If there isn't a fully supported solution at this time, can you provide a bit more detail as to how you disabled the compact job and what implications it may have if I were to do that as well? 

Thanks.

**Comment by littleskunk** [comment]
@doransmestad https://github.com/Storj/core/blob/master/lib/storage/manager.js#L168-L177

Remove it but keep the callback. The problem you will get is that the full node will not free any disk space. At some point you get paid for 7TB only but still 8TB blocked on your hard drive. That is what this function would do.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
