### ISSUE TITLE
 failed to start share

### ISSUE THREAD

**Issue by Puychack** [Storj/storjshare-daemon#119]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.5.2, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.9.5
```

### Expected Behavior

Before upgrade to v2.5.2, I could load more than 10 shares

### Actual Behavior

Just after upgrading storjshare fail to load more than 5 shares with the message " failed to start share, reason: insufficient system resources available"

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Load previous saved state with "storjshare load -s" or load shares one by one.

**Comment by Puychack** [comment]
Downgrading to v2.5.1 solved the problem. All shares are loaded again.

**Comment by littleskunk** [comment]
On a single CPU system you would get the error message on the first farmer already. Looks like a bug to me.

Workaround:
Run `storjshare daemon --unsafe` to disable the validation.

**Comment by felixbrucker** [comment]
I can see the reasons to implement such safeguarding steps, but there is a problem:
- one decides to start the share with `--unsafe`
- one executes `storjshare save` to store the running config
- one restarts the system
- one starts the daemon and loads the previous running config via `storjshare daemon && storjshare load`

### Expected Behavior

storjshare saved all the supplied params (including `--unsafe`) and starts all shares

### Actual Behavior

shorjshare does not save the `--unsafe` param and fails to startup the remaining shares

**Comment by ordtrogen** [comment]
I have the same problem since upgrading to new daemon version. Nothing substantial to add, just providing specs of my environment.

storjshare --version
  * daemon: 2.5.2, core: 6.4.2, protocol: 1.1.0

node --version
v7.9.0

I have been running two shares for quite a while on an old laptop. First share is allocated on the internal drive (120G) and the second on an external USB connected HD (500G). Due to problems with too high ratio of "timed out"/"sending" (in the logs) I have reduced the concurrency setting to 1. But apart from that everything has been running fine.

After upgrading to 2.5.2 I can start either of the shares, but when I try to start the second, it terminates with the message "failed to start share, reason: insufficient system resources available". There is no logfile created and no entry in the deamon log. 

I run a minimal Arch Linux installation. No desktop environment or GUI. All access is from my Windows machine via a TTY over SSH. 

OS: Arch Linux i686
Model: EasyNote MH35 PB99QD0091
Kernel: 4.10.13-1-ARCH
Shell: bash 4.4.12
CPU: Intel Pentium Dual T2310 (2) @ 1.467GHz
GPU: Silicon Integrated Systems [SiS] 771/671 PCIE VGA Display Adapter
Memory: 256MiB / 2902MiB

**Comment by ordtrogen** [comment]
Maybe begin by outputting something about what system resource ran out. Either to the console or a log file

**Comment by ordtrogen** [comment]
I'm guessing that @littleskunk refers to this piece of code (api.js, line 87) since someone with the same username and avatar ( :-) ) mentioned it in the rocketchat.

if (this.shares.size + 1 >= cpus().length && !unsafeFlag) {
  return callback(new Error('insufficient system resources available'));
}

So, my random stranger guessing on somebody elses code would be:

- cpus().length is the number of cpu cores.
- assuming that the new share has not yet been created when this function is called, and that we can run one share per core
- shouldn't the test just be 
  if (this.shares.size >= cpus().length && !unsafeFlag)
?

(this may be a terribly naïve comment, but hey, you published the code on github!)

**Comment by Puychack** [comment]
Seeing the bug fix for v2.5.3, it looks like allowing only 1 share per node is now a feature and not a bug ??
So I agree with @felixbrucker, unsafe information should be saved with shares details.

**Comment by littleskunk** [comment]
Be carefull with --unsafe. I has this name for a reason. Long term better reduce the number of nodes. The last stress test had pretty clear results. My farmer was not able to relay contract PUBLISH messages because my neighboors are running more farmer than there hardware can handle. At the moment we have these situations only for a few hours per week but what will happen if the renter start uploading more and more shards?

**Comment by ordtrogen** [comment]
It seems like this issue could be closed now.
