### ISSUE TITLE
(Auto-)Update Mechanism

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-daemon#133]
Add a feature to have a command to issue an update for storjshare-daemon

for example when you type storjshare-daemon update

it could run some sort of npm update storjshare-daemon command  (would have to temporarily stop the storjshare processes to perform the update and then start it when done)

Then with this could provide an auto-update mechanism to check for updates [every date/time] and if there is an update to perform it

**Comment by payne8** [comment]
Turns out that using `snap refresh` doesn't do the automatic update that snaps should do.

https://snapcraft.io/docs/core/usage

I didn't see anything in the docs about updating either. Here is how I had to figure out how to update:

```bash
which storjshare
returned -> /usr/bin/storjshare

ls -la /usr/bin/* | grep storjshare
pointed me to ../lib/node_modules/storjshare-daemon
```
Then I was confident I could update using `npm install storjshare-daemon -g`

**Comment by tempestb** [comment]
I think an auto-update might be difficult because the daemon kind of runs without outputting to the console unless called upon.  And you would want it to notify and request permission to update and not just update on its own.  I don't think everyone likes the idea of an application installing itself without permission.  

It could, of course, output that information in the log or during a status.  

I would probably make it so it informs on a status that there is an update available for Core/Daemon and then let the user decide how they want to update manually.  Assuming we fix up Snap at some point, the less adapt user could use Snap Refresh, where as those that understand the syntax or have unique environments can use npm or potentially their own make process to get it updated.  

If adding it to status is agreeable, I could work on that if anyone wants me to.  But I don't know enough about Snap to take that on right now.  So someone else would have to work on that part.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
