### ISSUE TITLE
Error : share is already running

### ISSUE THREAD

**Issue by Puychack** [storj/storjshare-daemon#141]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.5.4
```

Replace the values below using the output from `node --version`.

```
6.10.3
```

### Expected Behavior

 "storjshare restart -i" is expected to gracefully restart indicated share

### Actual Behavior

Under high I/O load (disk busy during shard reaping) it throws the following error message :
"share xxxxx is already running"

```
 - This problem occurs after stress tests. The daily shard reaping takes a long time to finish and is very I/O intensive following a big shard download (> 1 GBytes  / day).
 - Doing a manual stop, waiting 15 seconds and a manual start solve the problem.
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
