### ISSUE TITLE
HTTPS shard server support for web browsers

### ISSUE THREAD

**Issue by super3** [storj/storjshare-daemon#15]
Streamline the setup of using HTTPS for the shard server so that shards can be served to a web browser without running into mixed-content security policy blocks.

This could be done with integrating: https://certbot.eff.org/ and other configuration options.

Moved from [https://github.com/Storj/storjshare-cli/issues/242](https://github.com/Storj/storjshare-cli/issues/242).

**Comment by bookchin** [comment]
Implemented in `storjd` (SSL), LE certificate automation implemented in https://github.com/Storj/storjshare-dns

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
