### ISSUE TITLE
Limit/Cap Farmer Bandwidth

### ISSUE THREAD

**Issue by super3** [storj/storjshare-daemon#17]
Highly requested feature from users. User are using their network line for some other task, or have some terrible ISP that caps their Internet. They would like to add a setting to limit/cap their bandwidth usage. 

Note that there are already 3rd party applications that can do this, but users would like native support:

- Windows: Net Balancer
- Mac: Waterroof or Noobproof
- Linux: Wondershaper

#### Duplicates
https://github.com/Storj/storjshare-cli/issues/150
https://github.com/Storj/storjshare-gui/issues/281
https://github.com/Storj/storjshare-gui/issues/361
https://github.com/Storj/core/issues/552

**Comment by BlackDuck888** [comment]
For Linux trickle could be interesting, because you can control a single process.

**Comment by yuilleb** [comment]
Thanks for the recommendation of trickle @BlackDuck888. I started storjshare after shutting it down for 2 months while waiting for some updates. However the bandwidth usage is so bad computers on my network are losing internet connectivity from dropped packets. It would be best to have this as a builtin feature such as torrent clients offer. Is there any way to run trickle against the daemon process? In the mean time I'm forced to shut down storj again until there is an update for this problem.

**Comment by bookchin** [comment]
Implemented in `storjd`

**Comment by jflowers1974** [comment]
This needs to be further built out and documented.  Would be a huge (yuge?) positive for us with cap's.

**Comment by bookchin** [comment]
This has been implemented as a kad2 plugin:
https://github.com/kadtools/kad-hibernate

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
