### ISSUE TITLE
Restrict node operator to single payout address

### ISSUE THREAD

**Issue by ssa3512** [Storj/storjshare-daemon#174]
Per Storj, due to the way payouts are calculated a node operator should only run a single payout address for all nodes.

We should restrict a node operator to a single payout address for all nodes running under a single daemon/gui instance.

When starting a node, check against any existing running nodes to verify the `paymentAddress` is equal to the `paymentAddress` field in the configuration file of the node being started. If it is not, present an error message indicating that all nodes must use the same payout address.

`Payment address 0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359 is being used on a concurrent share. Please update configuration of node ID {currently launching node} to reflect this payment address`

**Comment by littleskunk** [comment]
No. The problem is the payout caluclation and not the daemon setup. Adding this rule would only punish legit farmer. They will get problems if they try to change there payout address and they are not allowed to increase there security by using more than one payout address. Meanwhile bad farmer will simply bypass the new rule.
