### ISSUE TITLE
Remove tunneling from config when creating new node(s)

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-daemon#194]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.3
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

As the new protocol/core update removes tunneling it would be advisable to slowly break down the tunneling system, this implies removing the `min`, `max` and `maxTunnels` parameters from the config file when a new node is created. Maybe even remove it automatically from everyone's config file when a update is carried out.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Tunneling is added to the config file of new nodes even though it will be removed from the protocol. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
