### ISSUE TITLE
Exiting log monitoring kills daemon + log monitoring hangs

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-daemon#20]
### Package Versions

Windows 10 

Replace the values below using the output from `storjshare --version`.

```
2.0.3
```

Replace the values below using the output from `node --version`.

```
6.9.4
```

### Expected Behavior

Log monitoring does not hang, and closing the monitoring windows does not kill storjshare.

### Actual Behavior

When going into the log monitoring mode (e.g. `storjshare logs --nodeid 72d6daaa086a7e25d53c58234d03bf9594b78590 `) after storjshare-daemon is running it will freeze after a few seconds and when the CMD window is closed, it automatically kills Storjshare-daemon and a complete restart is necessary. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start storjshare
2. Start logging monitoring
3. kill logging monitoring window

**Comment by MeijeSibbel** [comment]
The CMD window is only refreshed when one opens the logfile with a text editor. Then when the file is closed, it has to be opened again by double clicking on the logfile before the CLD windows is updated again. There is a refresh issue.

**Comment by MeijeSibbel** [comment]
I can make a recording of this behavior if you want, let me know

**Comment by MeijeSibbel** [comment]
https://www.youtube.com/watch?v=KFvUFT86bxY&feature=youtu.be

**Comment by MeijeSibbel** [comment]
https://www.youtube.com/watch?v=j_iCAirYmGg&feature=youtu.be

**Comment by MeijeSibbel** [comment]
I hope the videos help to demonstrate what exactly the issues are.

**Comment by littleskunk** [comment]
1.) Please try it with baretail. It is the windows version of less and will open the file read only. Do you see the same behavior?
2.) That is a bug. If you close the CMD it will kill the process. As workaround please press Strg+C. That should exit gracefully.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
