### ISSUE TITLE
Let the user choose the preferred NTP server to check delta in configs

### ISSUE THREAD

**Issue by luzemario** [storj/storjshare-daemon#215]
### Package Versions

daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0

node
v6.11.0

### Expected Behavior

storjshare-daemon would check the time to measure delta to the NTP server closest to the node.

### Actual Behavior

storjshare-daemon chooses a NTP server inside a hardcoded pool to check the delta.

### Steps to Reproduce

1. run storjshare daemon, activate shares
2. watch for UDP/123 requests using a packet sniffer or firewall
3. Set a local NTP server recursive to a good/nearest NTP pool on the internet
4. configure your host to get NTP time from this server
5. storjshare does not use this server.

**Comment by luzemario** [comment]
The delta keeps changing after every server storjshare asks the time to compare. There is some bug in this process.

**Comment by littleskunk** [comment]
Pull request wellcome: https://github.com/Storj/core/blob/master/lib/utils.js#L277-L278

**Comment by tempestb** [comment]
Maybe we should display one delta at the top or bottom, rather than for each node?   Because I believe the delta we are seeing is just fetched at the time the node is displayed (Or a timer) and it's not actually used for anything vs the actual clock precision that is used for signatures.   I think one delta on the form would be enough unless Storjshare Daemon can somehow control nodes across devices that I'm unaware of.

If we agree that one delta would be enough, I would volunteer to work on this.  Shouldn't be too difficult to put together.  (With some exceptions for the unknowns)

**Comment by luzemario** [comment]
I have five nodes on the same machine. Is pointless to have delta calculation on five shares in this case. It can be better handled if tied to the storjshare-daemon process instead delta on every node.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
