### ISSUE TITLE
Duplicate Bridge connection

### ISSUE THREAD

**Issue by littleskunk** [storj/storjshare-daemon#250]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
GUI 7.0.0
Daemon 4.0.2-beta.1
Core 7.0.3
Protocol 1.2.0
```

Replace the values below using the output from `node --version`.

```
6.11.3
```

### Expected Behavior

Please describe the program's expected behavior.

One connection to the bridge.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"Connected to bridge: https://api.storj.io","timestamp":"2017-09-12T23:02:30.098Z"}
{"level":"info","message":"Connected to bridge: https://api.storj.io","timestamp":"2017-09-12T23:02:30.098Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start farming and take a look into the logfile

**Comment by braydonf** [comment]
I think that's just a duplicate log message.

**Comment by littleskunk** [comment]
https://github.com/Storj/core/blob/d9ebd93a4afdb80ad38e3aaf55e5ac89a42333d1/lib/network/farmer.js#L276
https://github.com/Storj/storjshare-daemon/blob/b4b4894059192f638032cb85ff4c97d1f0437624/script/farmer.js#L57

Remove one?

**Comment by braydonf** [comment]
Yeah

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
