### ISSUE TITLE
Shared Space goes over 100 %

### ISSUE THREAD

**Issue by denndsd** [storj/storjshare-daemon#276]
Hello,

I know there is already a Case with the same problem,
But the version of the Solution is outdated.
My Storjshare daemon say Shared: (104%)
I want to Share 50 GB but now there are 51,4 GB Shared.
My Storjshare Version : daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
Is there a solution ?

**Comment by tempestb** [comment]
It's possible for used space to be slightly above what is shared.  This is because shards are contained in LevelDB databases, and LevelDB compresses the data.  So Storjshare makes approximations about available storage size, and depending on what is happening with the data at any given time, those databases may be open (Uncompressed) and taking up more space than what is available.   

There is ongoing discussion to abandon LevelDB in favor of a file system architecture.  If/When that happens, it will potentially fix this problem.

At the same time, Storjshare will not exceed the shared space significantly as your node will stop sending ALLOC messages to receive new data now that it is full.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
