### ISSUE TITLE
Question: How to upgrade storjshare-daemon ?

### ISSUE THREAD

**Issue by yepla** [Storj/storjshare-daemon#292]
Hello,

I have install storjshare-daemon like explain with:

npm install --global storjshare-daemon

I m not know anything about node and npm could you please tell me how i can upgrade to the last version of storjshare-daemon ?

I want to know too when i need to make an upgrade of storjshare-daemon ?

I mean how know when a new version is available ?

This 2 questions are easy for some but i really don't know ...

Could be great to say on the main page of the project because it could help some people ...

Thanks.

**Comment by tempestb** [comment]
Exactly the same way you installed it for updates.

npm install -g storjshare-daemon

None of your settings will change.  So it will operate as per usual unless some new feature has been added, but if so there is help in the release notes.  

Also, you can join us on the Storj Rocket.Chat at https://community.storj.io   (Although at the time I am writing this, it is down as they apply fixes, but it is almost always up otherwise)   And join the room #storjshare with any questions you may have.   We always have admins there to assist.  

We also announce updates in the #announcements channel, and you can find information in #payouts about your payout and other questions you may have.

Thanks!
Kevin "Knowledge" Baird
