### ISSUE TITLE
Error compilation of CL.exe on Windows 7

### ISSUE THREAD

**Issue by vyscarm** [storj/storjshare-daemon#295]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
??? not installed ???
```

`node --version`.

```
8.9.0
```

`npm --version`:
```
5.5.1
```

### Expected Behavior

Hello!
I'm trying to install storjshare-daemon on the guest OS Windows 7 (on Parallels).
I use the instruction [https://github.com/Storj/storjshare-daemon/](https://github.com/Storj/storjshare-daemon/).

At the last step on the command
**npm install --global storjshare-daemon**
there is an error.

I enclose a screenshot and a log:

![2_error_install_storj-daemon](https://user-images.githubusercontent.com/15012781/33027023-0a330268-ce23-11e7-92a8-79f5929ae1d9.png)

[2017-11-20T12_20_05_576Z-debug.log] (https://github.com/Storj/storjshare-daemon/files/1488151/2017-11-20T12_20_05_576Z-debug.log)

Help, please, to figure it out.
Thank you.

--------

Здравствуйте! 
Пытаюсь установить storjshare-daemon на гостевой Windows 7 (на Parallels).
Использую инструкцию [https://github.com/Storj/storjshare-daemon/](https://github.com/Storj/storjshare-daemon/) .

На последнем шаге на команде 
**npm install --global storjshare-daemon**
возникает ошибка.

Прилагаю скриншот и лог:

![2_error_install_storj-daemon](https://user-images.githubusercontent.com/15012781/33027023-0a330268-ce23-11e7-92a8-79f5929ae1d9.png)

[2017-11-20T12_20_05_576Z-debug.log](https://github.com/Storj/storjshare-daemon/files/1488151/2017-11-20T12_20_05_576Z-debug.log)

Помогите, пожалуйства, разобраться в чём дело.
Спасибо.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
![2_error_install_storj-daemon](https://user-images.githubusercontent.com/15012781/33027023-0a330268-ce23-11e7-92a8-79f5929ae1d9.png)
[2017-11-20T12_20_05_576Z-debug.log](https://github.com/Storj/storjshare-daemon/files/1488151/2017-11-20T12_20_05_576Z-debug.log)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Hello!
I'm trying to install storjshare-daemon on the guest OS Windows 7 (on Parallels).
I use the instruction https://github.com/Storj/storjshare-daemon/.

At the last step on the command
**npm install --global storjshare-daemon**
there is an error.

I enclose a screenshot and a log:

![2_error_install_storj-daemon](https://user-images.githubusercontent.com/15012781/33027023-0a330268-ce23-11e7-92a8-79f5929ae1d9.png)

[2017-11-20T12_20_05_576Z-debug.log] (https://github.com/Storj/storjshare-daemon/files/1488151/2017-11-20T12_20_05_576Z-debug.log)

Help, please, to figure it out.
Thank you.

**Comment by littleskunk** [comment]
Looks like the C compiler is not working on your System.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
