### ISSUE TITLE
[Feature] Save logs in different folders at the start of the new month

### ISSUE THREAD

**Issue by sdalmeida** [storj/storjshare-daemon#302]
### Package Versions

```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

```
v9.2.0
```

### Expected Behavior

Logs should be placed under folders, in respective to the current month.
Example:
If you `cd` into the logs folder and type in `ls`, you should see the following structure.
```
...
/path-to-log/September-2017/
/path-to-log/October-2017/
/path-to-log/November-2017/
...
```
Once the new month starts, `storjshare` should create a new folder and place the new logs there.

### Actual Behavior
All logs are being placed under the same folder. This is not optimal for when running the [ node upload/download script](https://docs.storj.io/docs/check-nodes-uploads-and-downloads-paid-and-unpaid)

**Comment by petitchevalroux** [comment]
imho it's not a storjshare-daemon feature. It's better to use a dedicated tool like logrotate

**Comment by simon66** [comment]
It should be a feature since storjshare creates these logs.

**Comment by littleskunk** [comment]
Logrotate will outperform everything we could implement...

**Comment by simon66** [comment]
@littleskunk 
In that case, can `logrotate` be included and used when creating logs? Or your recommendation is that I just leave everything at the default and write a `logrotate` cron job that triggers at the end on the month?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
