### ISSUE TITLE
insecure control socket

### ISSUE THREAD

**Issue by akostadinov** [storj/storjshare-daemon#316]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.9.3
```

### Expected Behavior

storj-daemon requires some form of authentication before accepting client commands. This can easily be achieved by a secure token/certificate in user home directory. In a similar way how chronyd/ntpd only allow commands from authenticated clients. And the auth key is secured by means of filesystem permissions.

### Actual Behavior

storj-daemon listens to an insecure local tcp socket. Any process on the same machine can have full control of the nodes and (as I read elsewhere) obtain nodes private keys.

This is unacceptable because any low-privilege processes and daemons (if compromised)  can obtain control over the sharing daemon and nodes. Even more so in multi-user environments.

### Steps to Reproduce

1. install storj share: useradd storj; npm install ...; storjshare daemon; storjshare load
2. create another user
3. as the second user, access daemon running under the first user

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
