### ISSUE TITLE
Error: Cannot find module './build/Release/diskusage.node'

### ISSUE THREAD

**Issue by sebastianheyn** [storj/storjshare-daemon#318]
### Package Versions
storjshare --version : not working
node version: v8.9.4

### Expected Behavior

Please describe the program's expected behavior.

should start

### Actual Behavior

module.js:540
    throw err;
    ^

Error: Cannot find module './build/Release/diskusage.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/node_modules/diskusage/index.js:1:76)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. npm install -g --unsafe-perm storjshare-daemon
2. npm install -g --unsafe-perm diskusage
3. storjshare --version

**Comment by littleskunk** [comment]
please execute `npm install -g --unsafe-perm storjshare-daemon` and upload the npm debug log.

**Comment by stefanbenten** [comment]
Which OS and User are you using? @sebastianheyn

**Comment by themurph2k** [comment]
I am getting same error. I executed the requested command above. Results are attached.

I am on Windows 10 Pro 64 build 10.0.16299

[2018-02-13T01_35_59_459Z-debug.log](https://github.com/Storj/storjshare-daemon/files/1718288/2018-02-13T01_35_59_459Z-debug.log)
![fail](https://user-images.githubusercontent.com/31016195/36129308-2cd3c6d6-102c-11e8-8316-bac00ba70281.png)

**Comment by ekaitz-zarraga** [comment]
Hi, I don't know if it's going to help but I had the same issue with Nodejs 10 and moved to 8, removed everything and installed it again and worked.
When I installed it with node10 it didn't compile anything and in the 8 did.

I don't know the reason, maybe there were some rests of the older installation and that made it fail in the first try.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
