### ISSUE TITLE
What is the best way to upgrade to 8.6.0

### ISSUE THREAD

**Issue by metabsd** [storj/storjshare-daemon#323]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.9.4
```

### Expected Behavior

I use the latest version. git clone but I don't have the latest version. Suppose to be 8.6.0.

### Actual Behavior

I see 8.5.0

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. git pull
2. npm install -g
3. storjshare -V --> daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0

**Comment by kroko** [comment]
had this question already https://github.com/Storj/storjshare-daemon/issues/320

**Comment by stefanbenten** [comment]
Just execute the following commands:

```
storjshare save
storjshare killall
npm install -g storjshare-daemon
storjshare daemon
storjshare load
```

this should update to the latest Core Version, when NPM finds a newer version online.

**Comment by kroko** [comment]
thanks

```sh
storjshare save
storjshare killall
export CC=cc && export CXX=c++ && npm install storjshare-daemon -g
storjshare daemon
storjshare load
storjshare --version
daemon: 5.3.0, core: 8.6.0, protocol: 1.2.0
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
