### ISSUE TITLE
Daemon crashes when it receives invalid input

### ISSUE THREAD

**Issue by fcro** [storj/storjshare-daemon#325]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.13.0
```

### Expected Behavior
The daemon should reply with an error message.

### Actual Behavior
The daemon crashes without error.

### Steps to Reproduce

1. Connect to the daemon with `nc` or any similar network tool.
```
$ nc -vv localhost 45015
localhost.localdomain [127.0.0.1] 45015 (?) open
{"method":"methods","arguments":[{"start":"[Function]","stop":"[Function]","restart":"[Function]","status":"[Function]","killall":"[Function]","destroy":"[Function]","save":"[Function]","load":"[Function]"}],"callbacks":{"0":["0","start"],"1":["0","stop"],"2":["0","restart"],"3":["0","status"],"4":["0","killall"],"5":["0","destroy"],"6":["0","save"],"7":["0","load"]},"links":[]}
```
2. Send the following JSON-formatted string. I didn't try with other JSON strings but I believe the result would be identical.
`
{"method":"status"}
`
nc should print the following before the connection gets closed:
`
sent 20, rcvd 382
`
3. Try to re-connect to the same port. The connection is refused because the daemon isn't running anymore.
```
$ nc -vv localhost 45015
localhost.localdomain [127.0.0.1] 45015 (?) : Connection refused
 sent 0, rcvd 0
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
