### ISSUE TITLE
'storjshare logs' command stops when the log file splits

### ISSUE THREAD

**Issue by Dri0m** [storj/storjshare-daemon#328]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.3.0, core: 8.6.0, protocol 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.9.4
```

### Expected Behavior

Command should keep tailing the log after the logfile that's being written into changes.

### Actual Behavior

Tailing stops and command outputs info message about no log available.

### Steps to Reproduce

1. storjshare logs -i <node>
2. wait until the node starts logging into a new file
3. observe

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
