### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by ghost** [storj/storjshare-daemon#331]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
none yet
```

Replace the values below using the output from `node --version`.

```
v8.10.0
```

### Expected Behavior

Compilation/Installation of StorjShare-cli

### Actual Behavior

Failure on **npm install --global storjshare-daemon**

```
npm WARN deprecated kad-logger-json@0.1.2: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad@1.6.5: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-quasar@1.2.4: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-fs@0.0.4: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-memstore@0.0.1: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io

> scrypt@6.0.3 preinstall /root/.nvm/versions/node/v8.10.0/lib/node_modules/storjshare-daemon/node_modules/scrypt
> node node-scrypt-preinstall.js

module.js:545
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v8.10.0/lib/node_modules/storjshare-daemon/node_modules/scrypt/node-scrypt-preinstall.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 preinstall: `node node-scrypt-preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-20T21_50_13_190Z-debug.log
```

### Steps to Reproduce

downloaded and followed instructions to compile from github page

thank you

**Comment by MrJacK67** [comment]
Please see this reply : [296](https://github.com/Storj/storjshare-daemon/issues/296#issuecomment-346342608)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
