### ISSUE TITLE
Node always restarts after upgrade to 7.3.2

### ISSUE THREAD

**Issue by pixelpox** [storj/storjshare-daemon#333]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
GUI 7.3.2
Daemon 5.3.0
Core 8.6.0
Protocol 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.10.0
```

### Expected Behavior

Storj to run in a normal fashion

### Actual Behavior

Since the upgrade 7.3.2->7.3.4 the nodes in storj will restart on a regular basis and turn off within the hour. No longer get any allocs in the dashboard let alone get any received. 

Downgrading back to 7.3.2 resumes normal opertation. Running it in the last 24 hours I've been getting the alloc messages and receiving data. I have been engaged with Aleksey for the last few days to diagnose the issue over on the [support board
](https://docs.storj.io/v1.1/discuss/5aaba17291cb63004de5df31) what will contain the wider picture of whats been tested. 

### Steps to Reproduce

1. Install fresh copy of Xubuntu
2. Install Storj 7.3.2
3. upgrade to 7.3.4 ($sudo dpkg -r storjShare $sudo dpkg -i storj.deb)
4. Run storjShare

Thanks for any help on this,
Simon

**Comment by silaxe** [comment]
Have you been able to solve your problem?

For my part, Storjshare currently shows "20 restarts", 1 alloc (0 received) and the node regularly switches off.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
