### ISSUE TITLE
storjshare should set non-zero exit code on failure

### ISSUE THREAD

**Issue by mtlynch** [storj/storjshare-daemon#335]
### Package Versions

```bash
$ storjshare --version
daemon: 5.3.1, core: 8.7.2, protocol: 1.2.0

$ node --version
v8.11.1
```

### Steps to Reproduce

Attempt to start a farmer with an incomplete config file:

```bash
$ storjshare daemon
$ wget https://raw.githubusercontent.com/Storj/storjshare-daemon/master/example/farmer.config.json
$ storjshare start --config farmer.config.json

  failed to start node, reason: invalid payout address
$ echo $?
0
```

### Expected Behavior

Exit code is set to a non-zero value, to represent failure, e.g.

```bash
$ echo $?
1
```

### Actual Behavior

Exit code is set to zero, implying success:

```bash
$ echo $?
0
```

This creates problems for developers who wish to write shell scripts or use configuration management tools to automate deployment.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
