### ISSUE TITLE
Storj writes error output inconsistently between STDOUT and STDERR

### ISSUE THREAD

**Issue by mtlynch** [storj/storjshare-daemon#336]
### Package Versions

```bash
$ storjshare --version
daemon: 5.3.1, core: 8.7.2, protocol: 1.2.0

$ node --version
v8.11.1
```

### Steps to Reproduce

When the user calls `storjshare create` with an invalid payment address, the error is written to STDERR:

```bash
$ storjshare create --noedit --outfile /tmp/a.json 1> /tmp/stdout-output.txt 2> /tmp/stderr-output.txt
$ cat /tmp/stdout-output.txt
$ cat /tmp/stderr-output.txt

  no payment address was given, try --help
```

When the user calls `storjshare create` with an invalid output path, the error is written to STDOUT:

```bash
$ storjshare create --noedit --outfile /notexists/a.json --storj "0x0000000000000000000000000000000000000000" 1> /tmp/stdout-output.txt 2> /tmp/stderr-output.txt
$ cat /tmp/stdout-output.txt

  failed to write config, reason: ENOENT: no such file or directory, open '/notexists/a.json'
$ cat /tmp/stderr-output.txt
```

### Expected Behavior

Storj writes all error output to stderr.

### Actual Behavior

Storj writes some errors to stdout and some errors to stderr.

This creates problems for developers who wish to write shell scripts or use configuration management tools to automate deployment.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
