### ISSUE TITLE
Can't set custom log path/file

### ISSUE THREAD

**Issue by skulko** [storj/storjshare-daemon#342]
I changed 'loggerOutputFile' to a different file/location but storj is still using the default path/files for logging. 

### Package Versions
```
daemon: 5.3.1, core: 8.7.2, protocol: 1.2.0
```

Node

```
v9.10.0
```

### Expected Behavior

Storj uses new path and file for logging.

### Actual Behavior

original log file is still being used($HOME/.config/storjshare/logs/[nodeid]_date.log)

### Steps to Reproduce

1. change "loggerOutputFile"
2. restart daemon

**Comment by stefanbenten** [comment]
Can you post the path you entered in your config as well as a permission output like `la -la` of that folder?

**Comment by skulko** [comment]
sorry, I guess that 'storjshare-stop -i ... ' was not enough. I could get it done with 'storjshare-destroy -i ...' and 'storj-start -c ...'

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
