### ISSUE TITLE
Tighter integration between Daemon process and farm processes

### ISSUE THREAD

**Issue by CJClaude** [storj/storjshare-daemon#38]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

One single master location to determine basic problems.

### Actual Behavior

Daemon should know WHY a farm process has stopped and included that on the status display for anything not in a "running" state.  Initally, simple issues, like "Failed to parse configuration file", "Port in use", "Other process error", "Unknown - other error", etc. would be helpful.

Key is that this should be sent back ANY time a process terminates voluntarily, even if the process log level is set to 0.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
