### ISSUE TITLE
Feature/Idea: storjshare-logs

### ISSUE THREAD

**Issue by BlackDuck888** [storj/storjshare-daemon#41]
If storjshare-logs is run without a nodeid it shows the output of all running nodes like `pm2 logs`

**Comment by littleskunk** [comment]
How about `pm2 flush`? I am missing this command as well.

**Comment by akostadinov** [comment]
I would say, at least print node ids and example syntax. e.g. I was trying `storjshare logs <id>` and it didn't indicate I have to specify `-i`. Just would be a little more user friendly.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
