### ISSUE TITLE
Storjshare permissions

### ISSUE THREAD

**Issue by CJClaude** [storj/storjshare-daemon#43]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.1.2, core: 6.0.15, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

Access to deamon should be restricted by userid that launches it.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Currently all users on a Linux box can fully control the storjshare daemon, issuing killall's at will.  Access is only limited by OS filesystem permissions on things like log files.

The ability of any user on the system to terminate the activities started by another user is not appropriate.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
