### ISSUE TITLE
storjshare create failure when daemon not running

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-daemon#93]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.10.0
```

### Expected Behavior

When you attempt to create a storjshare config file without the daemon running it should error out in a friendly way to say daemon not running please start it first

### Actual Behavior

When you perform storjshare create without the daemon running the following error occurs

```
failed to write config, reason: ENOENT: no such file or directory, open 'C:\Users\ContainerAdministrator\.config\stoto write config, reason: ENOENT: no such file or directory, open 'C:\Users\ContainerAdministrator\.config\sto.........
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ensure the storjshare daemon is not running
2. run storjshare create --sjcx paymentaddress
3. then it fails

**Comment by MitchTalmadge** [comment]
This tripped me up, thanks for reporting it

**Comment by johnantoni** [comment]
@computeronix same here, any ideas how to resolve?

I tried creating the .config directory but kept on failing, must be missing something

**Comment by johnantoni** [comment]
Ok, got something running, did:

    storjshare create --sjcx [token] --size 800GB --storage /home/john/storjshare --outfile /home/john/config

That creates a config file that I then run with using:

    storjshare daemon start --config /home/john/config

Checking with "ps aux | grep storjshare" and it's running ok, monitoring now to see how things progress.

**Comment by aleitner** [comment]
I'm not having this issue on  daemon: 3.4.2. Does this still happen on the latest version for anyone?

**Comment by johnantoni** [comment]
@aleitner installed the latest version, still errors out about the directory not being there but once the .config, etc directories are created manually then it's fine. not sure why it happens.

also found out the right way to start the daemon is

storjshare daemon start

and then:

storjshare start --config config.json

to start your share, just starting the daemon won't do anything 🤦‍♂️

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
