### ISSUE TITLE
if storjshare daemon not running start it for user

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-daemon#94]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.10.0
```

### Expected Behavior

When you perform storjshare commands that require the daemon and its not running, start the daemon for the user

### Actual Behavior

if you perform commands that require storjshare daemon to run -- the program says please start the daemon first

### Steps to Reproduce

1. run a storjshare command that requires the daemon without the daemon running

**Comment by calvintam236** [comment]
Totally agree! I tried to dockerize `storjshare-daemon`, but `start` command requires the daemon to be started first... Need to find a workaround.

**Comment by calvintam236** [comment]
I just found a workaround solution #68 without starting the daemon.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
